version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      #- '-alertmanager.url=http://alertmanager:9093'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitoring
      - traefik
      - chat_default
    labels:
      - "traefik.frontend.rule=Host: prometheus.cadu.vps.etica.ai"

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3100:3000
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - config.monitoring
    labels:
      - "traefik.frontend.rule=Host: grafana.cadu.vps.etica.ai"
    networks:
      - monitoring
      - traefik # TODO: change this (fititnt, 2017-09-15 04:49 BRT)

networks:
  monitoring:
    driver: bridge
  traefik:
    external:
      name: chat_default
  chat_default:
    external:
      name: chat_default