version: '3'

volumes:
  prometheus_data: {}
  #grafana_data: {}

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      #- '-alertmanager.url=http://alertmanager:9093'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitoring
      - traefik
      - chat_default
    labels:
      - "traefik.frontend.rule=Host: prometheus.cadu.vps.etica.ai"

networks:
  monitoring:
    driver: bridge
  traefik:
    external:
      name: chat_default
  chat_default:
    external:
      name: chat_default