version: '2'

services:
  prometheus:
    image: prom/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./data/prometheus/:/prometheus
    expose:
      - 9090
    ports:
      - 9090:9090