version: '2'

services:
  traefik:
    image: traefik
    command: --web --docker --docker.domain=cadu.vps.etica.ai --logLevel=DEBUG
    #command: traefik --docker --acme=true --acme.domains='chat.etica.ai' --acme.email='postmaster@etica.ai' --acme.entrypoint=https --acme.storagefile=acme.json --defaultentrypoints=http --defaultentrypoints=https --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' --entryPoints='Name:https Address::443 TLS.Certificates:'
    networks:
      - webgateway
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml

networks:
  webgateway:
    driver: bridge